import type { Buffer } from "node:buffer";
import type { GeneratedFile, ModFeature, ModSpec } from "../types.js";
import { generateBlock } from "./block.js";
import { generateCommand } from "./command.js";
import { generateItem } from "./item.js";
import { renderMainClass } from "./mainClass.js";
import { generateRecipe } from "./recipe.js";
import { generateRetextureBlock } from "./retextureBlock.js";
import { generateRetextureItem } from "./retextureItem.js";
import { generateToolOrWeapon } from "./toolWeapon.js";
import { emptyContribution, type FeatureContribution } from "./types.js";

export type CoverageStatus = "covered" | "uncovered";

export interface CoverageEntry {
  featureId: string;
  type: ModFeature["type"];
  status: CoverageStatus;
  reason?: string;
}

export interface DeterministicResult {
  /** True when every feature in the spec was generated by a template. */
  fullyCovered: boolean;
  /** Per-feature coverage with reasons for any uncovered entries. */
  coverage: CoverageEntry[];
  /** Files ready to write via safeWriteFiles. Only populated when fullyCovered. */
  files: GeneratedFile[];
  /** Reasons (one per uncovered feature) suitable for events / logs. */
  uncoveredReasons: string[];
  /** Free-form notes from generators (e.g. retint fell back to procedural). */
  noticeMessages: string[];
  /** One-line summary suitable for the codegen phase log. */
  summary: string;
}

/**
 * Feature types we know how to template. Anything outside this set goes to
 * AI fallback via runGeneration.
 */
const TEMPLATED: ReadonlySet<ModFeature["type"]> = new Set([
  "item",
  "block",
  "tool",
  "weapon",
  "recipe",
  "command",
  "retexture_item",
  "retexture_block",
]);

export interface GeneratorOptions {
  /**
   * Pre-computed AI textures keyed by feature.id, populated by
   * `precomputeAiTextures(spec)` before this entry point runs. Item/weapon/
   * tool generators look up their feature.id and use the AI bytes if present;
   * otherwise they fall through to the procedural texture path.
   *
   * Never populated for retexture_item / retexture_block — vanilla retextures
   * always go through the MODFORGE_VANILLA_ASSETS_DIR retint pipeline.
   */
  aiTextures?: ReadonlyMap<string, Buffer>;
  /**
   * Notice strings produced by the AI precompute step (e.g. "AI texture
   * unavailable for feature x — used procedural fallback"). Surfaced via
   * the generated README's Limitations section.
   */
  aiNotices?: ReadonlyArray<string>;
}

/**
 * Never throws on schema-valid input. If a generator unexpectedly throws —
 * or if a feature type has no template — the corresponding feature is marked
 * uncovered and the orchestrator returns `fullyCovered: false`, letting the
 * caller fall back to AI codegen safely.
 */
export function tryGenerateDeterministically(
  spec: ModSpec,
  opts: GeneratorOptions = {},
): DeterministicResult {
  const coverage: CoverageEntry[] = [];
  const merged = emptyContribution();
  const uncoveredReasons: string[] = [];

  for (const feature of spec.features) {
    if (!TEMPLATED.has(feature.type)) {
      const reason = `feature "${feature.id}" has unsupported type "${feature.type}"`;
      coverage.push({ featureId: feature.id, type: feature.type, status: "uncovered", reason });
      uncoveredReasons.push(reason);
      continue;
    }
    try {
      const c = generateForFeature(spec, feature, opts.aiTextures);
      mergeInto(merged, c);
      coverage.push({ featureId: feature.id, type: feature.type, status: "covered" });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      const reason = `feature "${feature.id}" (${feature.type}) could not be templated: ${msg}`;
      coverage.push({ featureId: feature.id, type: feature.type, status: "uncovered", reason });
      uncoveredReasons.push(reason);
    }
  }

  if (opts.aiNotices && opts.aiNotices.length > 0) {
    merged.noticeMessages.push(...opts.aiNotices);
  }

  if (uncoveredReasons.length > 0) {
    return {
      fullyCovered: false,
      coverage,
      files: [],
      uncoveredReasons,
      noticeMessages: merged.noticeMessages.slice(),
      summary: `falling back to AI codegen — ${uncoveredReasons.length} uncovered feature(s)`,
    };
  }

  const files = collectFiles(spec, merged);
  return {
    fullyCovered: true,
    coverage,
    files,
    uncoveredReasons: [],
    noticeMessages: merged.noticeMessages.slice(),
    summary: `templates covered all ${spec.features.length} feature(s)`,
  };
}

function generateForFeature(
  spec: ModSpec,
  feature: ModFeature,
  aiTextures?: ReadonlyMap<string, Buffer>,
): FeatureContribution {
  switch (feature.type) {
    case "item":
      return generateItem(spec, feature, aiTextures?.get(feature.id));
    case "block":
      return generateBlock(spec, feature);
    case "tool":
    case "weapon":
      return generateToolOrWeapon(spec, feature, aiTextures?.get(feature.id));
    case "recipe":
      return generateRecipe(spec, feature);
    case "command":
      return generateCommand(spec, feature);
    case "retexture_item":
      // Vanilla retextures NEVER use AI — always go through the vanilla
      // asset retint pipeline (MODFORGE_VANILLA_ASSETS_DIR), regardless of
      // whether AI textures are enabled.
      return generateRetextureItem(spec, feature);
    case "retexture_block":
      return generateRetextureBlock(spec, feature);
  }
}

function mergeInto(dest: FeatureContribution, src: FeatureContribution): void {
  dest.noticeMessages.push(...src.noticeMessages);
  dest.imports.push(...src.imports);
  dest.fieldDecls.push(...src.fieldDecls);
  dest.itemRegisters.push(...src.itemRegisters);
  dest.blockRegisters.push(...src.blockRegisters);
  dest.commandRegisters.push(...src.commandRegisters);
  dest.extraJavaFiles.push(...src.extraJavaFiles);
  dest.resources.push(...src.resources);
  Object.assign(dest.langEntries, src.langEntries);
  for (const [tag, values] of Object.entries(src.blockTags)) {
    dest.blockTags[tag] = [...(dest.blockTags[tag] ?? []), ...values];
  }
}

function collectFiles(spec: ModSpec, merged: FeatureContribution): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push(renderMainClass(spec, merged));
  files.push(...merged.extraJavaFiles);
  files.push(...merged.resources);

  if (Object.keys(merged.langEntries).length > 0) {
    files.push({
      path: `src/main/resources/assets/${spec.modId}/lang/en_us.json`,
      content: JSON.stringify(merged.langEntries, null, 2) + "\n",
    });
  }

  for (const [tagPath, values] of Object.entries(merged.blockTags)) {
    const unique = Array.from(new Set(values));
    files.push({
      path: `src/main/resources/${tagPath}`,
      content:
        JSON.stringify({ replace: false, values: unique }, null, 2) + "\n",
    });
  }

  return files;
}
