import fs from "node:fs/promises";
import path from "node:path";
import type { ModSpec } from "../types.js";
import { config } from "../config.js";

export async function generateReadme(
  spec: ModSpec,
  projectPath: string,
  jarPath?: string,
): Promise<void> {
  const jarRel = jarPath ? path.relative(projectPath, jarPath) : "build/libs/<your-jar>.jar";
  const content = `# ${spec.modName}

${spec.description}

- **Mod ID:** \`${spec.modId}\`
- **Minecraft:** ${config.fabric.mcVersion} (Fabric)
- **Fabric Loader:** ${config.fabric.loaderVersion}+
- **Fabric API:** required

## Features

${spec.features.map((f) => `- **${f.name}** (${f.type}): ${f.description}`).join("\n") || "_(none)_"}

## Build

From the project root:

\`\`\`sh
gradle build
\`\`\`

The compiled jar will be at \`${jarRel}\`.

## Install

1. Install [Fabric Loader](https://fabricmc.net/use/installer/) for Minecraft ${config.fabric.mcVersion}.
2. Install [Fabric API](https://modrinth.com/mod/fabric-api) into your \`mods/\` folder.
3. Drop the built jar into the same \`mods/\` folder.
4. Launch the Fabric profile.

## Notes

${spec.assumptions.length ? `**Assumptions:**\n${spec.assumptions.map((a) => `- ${a}`).join("\n")}\n` : ""}
${spec.limitations.length ? `**Limitations:**\n${spec.limitations.map((l) => `- ${l}`).join("\n")}\n` : ""}
Generated by ModForge AI.
`;
  await fs.writeFile(path.join(projectPath, "README.md"), content, "utf8");
}
