import fs from "node:fs/promises";
import path from "node:path";
import { config } from "../config.js";
import type { ModSpec } from "../types.js";

/**
 * Pure README renderer (no I/O). Exported for testing — `generateReadme`
 * below wraps it with a file write.
 *
 * `extraLimitations` is appended to the spec's own limitations list. Used
 * by the deterministic generators to surface notes like "fell back to
 * procedural texture" without mutating the validated spec.
 */
export function renderModReadme(
  spec: ModSpec,
  jarPath?: string,
  extraLimitations: string[] = [],
): string {
  // The renderer doesn't know the project root, so show the conventional
  // Loom output path rather than fabricating a misleading relative.
  const jarFilename = jarPath ? path.basename(jarPath) : `${spec.modId}-${spec.modVersion}.jar`;
  const jarRel = `build/libs/${jarFilename}`;

  const sections: string[] = [];

  sections.push(`# ${spec.modName}`);
  if (spec.description) sections.push(`> ${spec.description}`);
  sections.push("_Generated by ModForge AI._");

  // Quick facts table.
  sections.push("## Quick facts");
  sections.push(
    [
      "| Field | Value |",
      "| --- | --- |",
      `| Mod name | **${spec.modName}** |`,
      `| Mod ID | \`${spec.modId}\` |`,
      `| Mod version | \`${spec.modVersion}\` |`,
      `| Minecraft | **${spec.mcVersion}** (Java Edition) |`,
      `| Mod loader | **Fabric** |`,
      `| Fabric Loader | \`>= ${config.fabric.loaderVersion}\` |`,
      `| Fabric API | **required** (separate jar) |`,
      `| Java | \`>= ${config.fabric.javaVersion}\` |`,
      `| JAR | \`${jarRel}\` |`,
    ].join("\n"),
  );

  // What this mod does.
  sections.push("## What this mod does");
  sections.push(spec.description || "(no description supplied)");

  // Features grouped by type.
  const featuresMd = renderFeatures(spec);
  if (featuresMd) sections.push(featuresMd);

  // Install.
  sections.push(renderInstallation(jarFilename));

  // Testing in Minecraft.
  sections.push(renderTesting(spec));

  // Assumptions.
  if (spec.assumptions.length > 0) {
    sections.push("## Assumptions");
    sections.push(spec.assumptions.map((a) => `- ${a}`).join("\n"));
  }

  // Limitations (spec + any extras the generators surfaced post-validation).
  const allLimitations = [...spec.limitations, ...extraLimitations];
  if (allLimitations.length > 0) {
    sections.push("## Limitations");
    sections.push(allLimitations.map((l) => `- ${l}`).join("\n"));
  }

  // Troubleshooting.
  sections.push(renderTroubleshooting(spec));

  return sections.join("\n\n") + "\n";
}

function renderFeatures(spec: ModSpec): string {
  const items: string[] = [];
  const blocks: string[] = [];
  const tools: string[] = [];
  const weapons: string[] = [];
  const recipes: string[] = [];
  const commands: string[] = [];
  const retextures: string[] = [];

  for (const f of spec.features) {
    switch (f.type) {
      case "item":
        items.push(`- \`${spec.modId}:${f.id}\` — **${f.name}**${f.description ? `: ${f.description}` : ""}`);
        break;
      case "block": {
        const d = f.details;
        const meta: string[] = [];
        if (d.hardness !== undefined) meta.push(`hardness ${d.hardness}`);
        if (d.requiresTool) meta.push(`requires tool`);
        if (d.miningTool) meta.push(`tool: ${d.miningTool}`);
        if (d.miningLevel) meta.push(`level: ${d.miningLevel}`);
        const metaStr = meta.length ? ` _(${meta.join(", ")})_` : "";
        blocks.push(
          `- \`${spec.modId}:${f.id}\` — **${f.name}**${metaStr}${f.description ? `: ${f.description}` : ""}`,
        );
        break;
      }
      case "tool":
        tools.push(`- \`${spec.modId}:${f.id}\` — **${f.name}** (custom Item subclass)${f.description ? `: ${f.description}` : ""}`);
        break;
      case "weapon": {
        const d = f.details;
        const extras: string[] = [];
        if (d.weaponType) extras.push(d.weaponType);
        if (d.knockback !== undefined) extras.push(`knockback ${d.knockback}`);
        if (d.durability !== undefined) extras.push(`durability ${d.durability}`);
        const extraStr = extras.length ? ` _(${extras.join(", ")})_` : "";
        weapons.push(
          `- \`${spec.modId}:${f.id}\` — **${f.name}**${extraStr}${f.description ? `: ${f.description}` : ""}`,
        );
        break;
      }
      case "recipe": {
        const d = f.details;
        const result = `\`${d.result.itemId}\` × ${d.result.count}`;
        const summary = d.shape === "shaped" ? `shaped → ${result}` : `shapeless → ${result}`;
        recipes.push(`- **${f.name}** — ${summary}`);
        break;
      }
      case "command": {
        const d = f.details;
        commands.push(
          `- \`/${d.commandName}\` — gives \`${d.action.itemId}\` × ${d.action.count} (operator level ${d.permissionLevel})${f.description ? `; ${f.description}` : ""}`,
        );
        break;
      }
      case "retexture_item":
      case "retexture_block":
        retextures.push(
          `- \`${f.details.vanillaTarget}\` — **${f.name}** (style: \`${f.details.textureStyle}\`, primary: \`${f.details.textureColor}\`)`,
        );
        break;
    }
  }

  const out: string[] = ["## Generated features"];
  if (items.length) out.push("### Items", items.join("\n"));
  if (blocks.length) out.push("### Blocks", blocks.join("\n"));
  if (tools.length) out.push("### Tools", tools.join("\n"));
  if (weapons.length) out.push("### Weapons", weapons.join("\n"));
  if (recipes.length) out.push("### Recipes", recipes.join("\n"));
  if (commands.length) out.push("### Commands", commands.join("\n"));
  if (retextures.length) out.push("### Vanilla retextures", retextures.join("\n"));

  if (out.length === 1) return ""; // nothing to render
  return out.join("\n\n");
}

function renderInstallation(jarFilename: string): string {
  return [
    "## Installation",
    "1. Install **Fabric Loader** for Minecraft 1.20.1: https://fabricmc.net/use/installer/",
    "2. Download **Fabric API** for Minecraft 1.20.1: https://modrinth.com/mod/fabric-api/versions?g=1.20.1",
    "3. Open your Minecraft `mods` folder:",
    "   - **macOS:** `~/Library/Application Support/minecraft/mods`",
    "   - **Windows:** `%appdata%\\.minecraft\\mods`",
    "   - **Linux:** `~/.minecraft/mods`",
    `4. Place the Fabric API jar **and** \`${jarFilename}\` into \`mods/\`.`,
    "5. Launch the **Fabric 1.20.1** profile in the Minecraft Launcher.",
  ].join("\n");
}

function renderTesting(spec: ModSpec): string {
  const out: string[] = ["## Testing in Minecraft"];

  // /give for items, blocks, tools, weapons (BlockItems share the block's id).
  const giveTargets: Array<{ id: string; label: string }> = [];
  for (const f of spec.features) {
    if (f.type === "item" || f.type === "block" || f.type === "tool" || f.type === "weapon") {
      giveTargets.push({ id: f.id, label: f.name });
    }
  }
  if (giveTargets.length > 0) {
    out.push("### `/give` commands");
    out.push("Open chat (cheats enabled) and run:");
    out.push("```");
    for (const t of giveTargets) {
      out.push(`/give @p ${spec.modId}:${t.id}`);
    }
    out.push("```");
  }

  // Custom commands.
  const customCommands = spec.features.filter((f) => f.type === "command");
  if (customCommands.length > 0) {
    out.push("### Custom commands");
    out.push("Run these in chat (operator level required):");
    out.push("```");
    for (const f of customCommands) {
      if (f.type === "command") out.push(`/${f.details.commandName}`);
    }
    out.push("```");
  }

  // Retexture guidance.
  const itemRetex = spec.features.filter((f) => f.type === "retexture_item");
  const blockRetex = spec.features.filter((f) => f.type === "retexture_block");
  if (itemRetex.length > 0 || blockRetex.length > 0) {
    out.push("### Vanilla retextures");
    out.push(
      "Open the Creative inventory and look at these vanilla items/blocks — their textures should be replaced with the new ones:",
    );
    const guidance: string[] = [];
    for (const f of itemRetex) {
      if (f.type !== "retexture_item") continue;
      const target = f.details.vanillaTarget;
      const path = target.replace(/^minecraft:/, "");
      guidance.push(
        `- **${prettyName(path)}** — \`${target}\` (the **item**, not its ore block — search "${path}" in Creative)`,
      );
    }
    for (const f of blockRetex) {
      if (f.type !== "retexture_block") continue;
      const target = f.details.vanillaTarget;
      const path = target.replace(/^minecraft:/, "");
      const facesNote =
        target === "minecraft:grass_block"
          ? " (top + side faces; the bottom is dirt and is not retextured)"
          : "";
      guidance.push(
        `- **${prettyName(path)}** — \`${target}\`${facesNote} (place a few in the world to see the new texture)`,
      );
    }
    out.push(guidance.join("\n"));
  }

  if (out.length === 1) {
    // No interactive features — just say so.
    out.push("This mod has no items, blocks, commands, or retextures to test interactively.");
  }
  return out.join("\n\n");
}

function renderTroubleshooting(spec: ModSpec): string {
  const lines = [
    "## Troubleshooting",
    "- **Mod doesn't appear in the Mods list.** Confirm both this jar **and** Fabric API are in `mods/`, and that you launched the **Fabric 1.20.1** profile (not vanilla or another mod loader).",
    "- **Game crashes with a Loom/version mismatch.** This mod targets Minecraft 1.20.1 only. Use the 1.20.1 Fabric profile.",
    "- **Item / block appears as a purple-and-black checker.** No texture was generated for that feature. Re-generate with a more descriptive prompt that mentions a color, or drop your own PNG into `assets/" + spec.modId + "/textures/{item,block}/<id>.png`.",
    "- **`/give` reports `no element of type item with key …`.** Verify the mod is loaded (check the Mods list), and use tab-completion after `/give @p " + spec.modId + ":` to see registered IDs.",
  ];
  if (spec.features.some((f) => f.type === "retexture_item" || f.type === "retexture_block")) {
    lines.push(
      "- **Vanilla retexture doesn't show up.** Resource-pack-style overrides only apply when the mod is in `mods/`. Make sure no other mod or resource pack is overriding the same texture later in the load order.",
    );
  }
  return lines.join("\n");
}

function prettyName(path: string): string {
  return path
    .replace(/_/g, " ")
    .replace(/\b\w/g, (m) => m.toUpperCase());
}

// ----------------------------------------------------------------------------

export async function generateReadme(
  spec: ModSpec,
  projectPath: string,
  jarPath?: string,
  extraLimitations: string[] = [],
): Promise<void> {
  const content = renderModReadme(spec, jarPath, extraLimitations);
  await fs.writeFile(path.join(projectPath, "README.md"), content, "utf8");
}
